# Generated by Django 4.1.7 on 2023-06-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_customer_order_orderitem_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
